<?php

return [
    'name' => 'cosmos',
    'author' => 'info@buzz.dev',
    'url' => 'https://buzz.dev',

    'settings' => [
        [
            'name' => 'direct_checkout',
            'label' => 'Direct Checkout',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Don\'t show the product overview page, go directly to the checkout page',
        ],
        [
            'name' => 'small_images',
            'label' => 'Small Images',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Show small images in the product overview page',
        ],
        [
            'name' => 'show_category_description',
            'label' => 'Show Category Description',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Show the category description in the product overview page/homepage',
        ],
         [
            'name' => 'spotlight-enabled',
            'label' => 'Spotlight Enabled',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Enable the background spotlight effect',
        ],
        [
            'name' => 'announcement_banner',
            'label' => 'Announcement Banner',
            'type' => 'markdown',
            'default' => '',
            'description' => 'HTML content for the announcement banner displayed above the navigation bar',
        ],
        [
            'name' => 'announcement_banner_enabled',
            'label' => 'Enable Announcement Banner',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Show or hide the announcement banner above the navigation bar',
        ],
         [
            'name' => 'show-home-page-plans-table',
            'label' => 'Show Home Page Plans Table',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Show the plans table on the home page',
        ],
        [
            'name' => 'show-home-page-products',
            'label' => 'Show Home Page Products',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Show products on the home page',
        ],
         [
            'name' => 'home-page-products-category',
            'label' => 'Home Page Products Category Slug',
            'type' => 'text',
            'default' => '',
            'description' => 'The category slug to show on the home page',
        ],
          [
            'name' => 'home-page-products-category-grid-columns',
            'label' => 'Home Page Products Category Grid Columns',
            'type' => 'number',
            'default' => 2,
            'description' => 'The number of columns to show on the home page',
        ],
          [
            'name' => 'show-support-sidebar-widget',
            'label' => 'Show Support Sidebar Widget',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Show the support sidebar widget on the dashboard',
        ],
           [
            'name' => 'show-discord-icon-navbar',
            'label' => 'Show Discord support Icon in Navbar',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Show the Discord icon in the navbar',
        ],
           [
            'name' => 'enable-search-bars',
            'label' => 'Enable Search Bars',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Enable the search bars (requires setup)',
        ],
          [
            'name' => 'shop-product-grid-columns',
            'label' => 'Shop Product Grid Columns',
            'type' => 'number',
            'default' => 2,
            'description' => 'The number of columns to show on the shop product page',
        ],
         [
            'name' => 'global_broadcast_enabled',
            'label' => 'Enable Global Broadcast Alert',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Show a global broadcast alert at the top of the sidebar/main content',
        ],
        [
            'name' => 'global_broadcast_title',
            'label' => 'Global Broadcast Title',
            'type' => 'text',
            'default' => '',
            'description' => 'Title for the global broadcast alert',
        ],
        [
            'name' => 'global_broadcast_content',
            'label' => 'Global Broadcast Content',
            'type' => 'markdown',
            'default' => '',
            'description' => 'Content for the global broadcast alert',
        ],
        [
            'name' => 'dark-primary',
            'label' => 'Primary - Brand Color',
            'type' => 'color',
            'default' => 'hsl(265, 92%, 69%)',
        ],
        [
            'name' => 'dark-secondary',
            'label' => 'Secondary - Brand Color',
            'type' => 'color',
            'default' => 'hsl(237, 33%, 60%)',
        ],
        [
            'name' => 'dark-neutral',
            'label' => 'Borders, Accents...',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 15%)',
        ],
        [
            'name' => 'dark-base',
            'label' => 'Base - Text Color',
            'type' => 'color',
            'default' => 'hsl(0, 0.00%, 96.90%)',
        ],
        [
            'name' => 'dark-muted',
            'label' => 'Muted - Text Color',
            'type' => 'color',
            'default' => 'hsl(0, 0.00%, 39.20%)',
        ],
        [
            'name' => 'dark-inverted',
            'label' => 'Inverted - Text Color',
            'type' => 'color',
            'default' => 'hsl(220, 14%, 60%)',
        ],
        [
            'name' => 'dark-background',
            'label' => 'Background - Color',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 9%)',
        ],
        [
            'name' => 'dark-background-secondary',
            'label' => 'Background - Secondary Color',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 15%)',
        ],
        [
            'name' => 'dark-background-gradient-start',
            'label' => 'Background - Gradient Start Color',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 8%)',
            'description' => 'The start color of the background gradient',
        ],
        [
            'name' => 'dark-background-gradient-end',
            'label' => 'Background - Gradient End Color',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 11%)',
            'description' => 'The end color of the background gradient',
        ],
        // Social Links
        [
            'name' => 'social-link-instagram',
            'label' => 'Social Link - Instagram',
            'type' => 'text',
            'default' => '',
        ],
        [
            'name' => 'social-link-discord',
            'label' => 'Social Link - Discord',
            'type' => 'text',
            'default' => 'https://discord.gg/buzz',
        ],
        [
            'name' => 'social-link-twitter',
            'label' => 'Social Link - Twitter',
            'type' => 'text',
            'default' => '',
        ],
        [
            'name' => 'social-link-linkedin',
            'label' => 'Social Link - LinkedIn',
            'type' => 'text',
            'default' => '',
        ],
        [
            'name' => 'social-link-youtube',
            'label' => 'Social Link - YouTube',
            'type' => 'text',
            'default' => '',
        ],

        [
            'name' => 'title1',
            'label' => 'Hero Title 1',
            'type' => 'text',
            'default' => 'Lightning Fast',
        ],
        [
            'name' => 'title2',
            'label' => 'Hero Title 2',
            'type' => 'text',
            'default' => 'Web Hosting',
        ],
        [
            'name' => 'hero_text',
            'label' => 'Hero Text',
            'type' => 'markdown',
            'default' => 'Deploy your websites with confidence. Our premium hosting infrastructure delivers unmatched performance, security, and reliability.',
        ],
        [
            'name' => 'button1text',
            'label' => 'Hero Button 1 Text',
            'type' => 'text',
            'default' => 'Get Started',
        ],
        [
            'name' => 'button1link',
            'label' => 'Hero Button 1 Link',
            'type' => 'text',
            'default' => '#',
        ],
        [
            'name' => 'button2text',
            'label' => 'Hero Button 2 Text',
            'type' => 'text',
            'default' => 'View Plans',
        ],
        [
            'name' => 'button2link',
            'label' => 'Hero Button 2 Link',
            'type' => 'text',
            'default' => '#',
        ],

        [
            'name' => 'features_section_title',
            'label' => 'Features Section Title',
            'type' => 'text',
            'default' => 'Everything You Need',
        ],
        [
            'name' => 'features_section_subtitle',
            'label' => 'Features Section Subtitle',
            'type' => 'text',
            'default' => 'Powerful features designed to help your business succeed online',
        ],
        [
            'name' => 'feature_1_icon',
            'label' => 'Feature 1 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-bolt',
        ],
        [
            'name' => 'feature_1_title',
            'label' => 'Feature 1 Title',
            'type' => 'text',
            'default' => 'Blazing Fast',
        ],
        [
            'name' => 'feature_1_description',
            'label' => 'Feature 1 Description',
            'type' => 'text',
            'default' => 'Experience top-tier speed and performance for all your sites.',
        ],
        [
            'name' => 'feature_2_icon',
            'label' => 'Feature 2 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-server',
        ],
        [
            'name' => 'feature_2_title',
            'label' => 'Feature 2 Title',
            'type' => 'text',
            'default' => 'Reliable Servers',
        ],
        [
            'name' => 'feature_2_description',
            'label' => 'Feature 2 Description',
            'type' => 'text',
            'default' => 'Our infrastructure is built for reliability and uptime.',
        ],
        [
            'name' => 'feature_3_icon',
            'label' => 'Feature 3 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-shield-alt',
        ],
        [
            'name' => 'feature_3_title',
            'label' => 'Feature 3 Title',
            'type' => 'text',
            'default' => 'Advanced Security',
        ],
        [
            'name' => 'feature_3_description',
            'label' => 'Feature 3 Description',
            'type' => 'text',
            'default' => 'Protect your data with industry-leading security features.',
        ],
        [
            'name' => 'feature_4_icon',
            'label' => 'Feature 4 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-globe',
        ],
        [
            'name' => 'feature_4_title',
            'label' => 'Feature 4 Title',
            'type' => 'text',
            'default' => 'Global Reach',
        ],
        [
            'name' => 'feature_4_description',
            'label' => 'Feature 4 Description',
            'type' => 'text',
            'default' => 'Serve your content quickly to users around the world.',
        ],
        [
            'name' => 'feature_big_icon',
            'label' => 'Feature Highlight Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-globe',
        ],
        [
            'name' => 'feature_big_title',
            'label' => 'Feature Highlight Title',
            'type' => 'text',
            'default' => 'Global CDN',
        ],
        [
            'name' => 'feature_big_description',
            'label' => 'Feature Highlight Description',
            'type' => 'text',
            'default' => 'Supercharge your website’s speed and reliability with our worldwide Content Delivery Network.',
        ],

        [
            'name' => 'reasons_section_title',
            'label' => 'Reasons Section Title',
            'type' => 'text',
            'default' => 'Why Choose Us?',
        ],
        [
            'name' => 'reasons_section_subtitle',
            'label' => 'Reasons Section Subtitle',
            'type' => 'text',
            'default' => 'We\'re not just another hosting provider. Here\'s what makes us different.',
        ],
        [
            'name' => 'reason_1_icon',
            'label' => 'Reason 1 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-bolt',
        ],
        [
            'name' => 'reason_1_title',
            'label' => 'Reason 1 Title',
            'type' => 'text',
            'default' => 'Instant Setup',
        ],
        [
            'name' => 'reason_1_description',
            'label' => 'Reason 1 Description',
            'type' => 'text',
            'default' => 'Get online in minutes with our instant provisioning.',
        ],
        [
            'name' => 'reason_1_stat',
            'label' => 'Reason 1 Stat',
            'type' => 'text',
            'default' => '1 min',
        ],
        [
            'name' => 'reason_1_stat_label',
            'label' => 'Reason 1 Stat Label',
            'type' => 'text',
            'default' => 'Setup Time',
        ],
        [
            'name' => 'reason_2_icon',
            'label' => 'Reason 2 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-server',
        ],
        [
            'name' => 'reason_2_title',
            'label' => 'Reason 2 Title',
            'type' => 'text',
            'default' => '99.9% Uptime',
        ],
        [
            'name' => 'reason_2_description',
            'label' => 'Reason 2 Description',
            'type' => 'text',
            'default' => 'Our servers are monitored 24/7 for maximum uptime.',
        ],
        [
            'name' => 'reason_2_stat',
            'label' => 'Reason 2 Stat',
            'type' => 'text',
            'default' => '99.9%',
        ],
        [
            'name' => 'reason_2_stat_label',
            'label' => 'Reason 2 Stat Label',
            'type' => 'text',
            'default' => 'Uptime',
        ],
        [
            'name' => 'reason_3_icon',
            'label' => 'Reason 3 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-shield-alt',
        ],
        [
            'name' => 'reason_3_title',
            'label' => 'Reason 3 Title',
            'type' => 'text',
            'default' => 'DDoS Protection',
        ],
        [
            'name' => 'reason_3_description',
            'label' => 'Reason 3 Description',
            'type' => 'text',
            'default' => 'Advanced DDoS protection keeps your site safe.',
        ],
        [
            'name' => 'reason_3_stat',
            'label' => 'Reason 3 Stat',
            'type' => 'text',
            'default' => '24/7',
        ],
        [
            'name' => 'reason_3_stat_label',
            'label' => 'Reason 3 Stat Label',
            'type' => 'text',
            'default' => 'Protection',
        ],
        [
            'name' => 'reason_4_icon',
            'label' => 'Reason 4 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-cloud',
        ],
        [
            'name' => 'reason_4_title',
            'label' => 'Reason 4 Title',
            'type' => 'text',
            'default' => 'Cloud Backups',
        ],
        [
            'name' => 'reason_4_description',
            'label' => 'Reason 4 Description',
            'type' => 'text',
            'default' => 'Daily backups ensure your data is always safe.',
        ],
        [
            'name' => 'reason_4_stat',
            'label' => 'Reason 4 Stat',
            'type' => 'text',
            'default' => 'Daily',
        ],
        [
            'name' => 'reason_4_stat_label',
            'label' => 'Reason 4 Stat Label',
            'type' => 'text',
            'default' => 'Backups',
        ],

        [
            'name' => 'faq_section_title',
            'label' => 'FAQ Section Title',
            'type' => 'text',
            'default' => 'Frequently Asked Questions',
        ],
        [
            'name' => 'faq_section_subtitle',
            'label' => 'FAQ Section Subtitle',
            'type' => 'text',
            'default' => 'Got questions? We\'ve got answers. Find everything you need to know about our hosting services.',
        ],
        [
            'name' => 'faq_1_question',
            'label' => 'FAQ 1 Question',
            'type' => 'text',
            'default' => 'How do I get started?',
        ],
        [
            'name' => 'faq_1_answer',
            'label' => 'FAQ 1 Answer',
            'type' => 'text',
            'default' => 'Simply choose a plan and follow the sign-up process to get started.',
        ],
        [
            'name' => 'faq_2_question',
            'label' => 'FAQ 2 Question',
            'type' => 'text',
            'default' => 'Can I upgrade my plan later?',
        ],
        [
            'name' => 'faq_2_answer',
            'label' => 'FAQ 2 Answer',
            'type' => 'text',
            'default' => 'Yes, you can upgrade or downgrade your plan at any time from your dashboard.',
        ],
        [
            'name' => 'faq_3_question',
            'label' => 'FAQ 3 Question',
            'type' => 'text',
            'default' => 'Is there a money-back guarantee?',
        ],
        [
            'name' => 'faq_3_answer',
            'label' => 'FAQ 3 Answer',
            'type' => 'text',
            'default' => 'We offer a 30-day money-back guarantee on all plans.',
        ],
        [
            'name' => 'faq_4_question',
            'label' => 'FAQ 4 Question',
            'type' => 'text',
            'default' => 'Do you provide support?',
        ],
        [
            'name' => 'faq_4_answer',
            'label' => 'FAQ 4 Answer',
            'type' => 'text',
            'default' => 'Yes, our support team is available 24/7 to assist you.',
        ],
        [
            'name' => 'faq_5_question',
            'label' => 'FAQ 5 Question',
            'type' => 'text',
            'default' => 'Can I transfer my existing website?',
        ],
        [
            'name' => 'faq_5_answer',
            'label' => 'FAQ 5 Answer',
            'type' => 'text',
            'default' => 'Absolutely, we offer free website migration for all new customers.',
        ],
        [
            'name' => 'faq_6_question',
            'label' => 'FAQ 6 Question',
            'type' => 'text',
            'default' => 'Are backups included?',
        ],
        [
            'name' => 'faq_6_answer',
            'label' => 'FAQ 6 Answer',
            'type' => 'text',
            'default' => 'Daily backups are included with every plan to keep your data safe.',
        ],

        [
            'name' => 'contact_section_title',
            'label' => 'Contact Section Title',
            'type' => 'text',
            'default' => 'Need Something Else?',
        ],
        [
            'name' => 'contact_section_subtitle',
            'label' => 'Contact Section Subtitle',
            'type' => 'text',
            'default' => 'Can\'t find what you\'re looking for? Our team is here to help you find the perfect hosting solution for your unique needs.',
        ],
        [
            'name' => 'contact_1_icon',
            'label' => 'Contact 1 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-comments',
        ],
        [
            'name' => 'contact_1_label',
            'label' => 'Contact 1 Label',
            'type' => 'text',
            'default' => 'Live Chat',
        ],
        [
            'name' => 'contact_1_value',
            'label' => 'Contact 1 Value',
            'type' => 'text',
            'default' => 'Available 24/7',
        ],
        [
            'name' => 'contact_2_icon',
            'label' => 'Contact 2 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-envelope',
        ],
        [
            'name' => 'contact_2_label',
            'label' => 'Contact 2 Label',
            'type' => 'text',
            'default' => 'Email Support',
        ],
        [
            'name' => 'contact_2_value',
            'label' => 'Contact 2 Value',
            'type' => 'text',
            'default' => 'support@hostingco.com',
        ],
        [
            'name' => 'contact_3_icon',
            'label' => 'Contact 3 Icon',
            'type' => 'text',
            'default' => 'fa-solid fa-phone',
        ],
        [
            'name' => 'contact_3_label',
            'label' => 'Contact 3 Label',
            'type' => 'text',
            'default' => 'Phone Support',
        ],
        [
            'name' => 'contact_3_value',
            'label' => 'Contact 3 Value',
            'type' => 'text',
            'default' => '1-800-HOSTING',
        ],
        [
            'name' => 'contact_button1_text',
            'label' => 'Contact Button 1 Text',
            'type' => 'text',
            'default' => 'Request Quote',
        ],
        [
            'name' => 'contact_button1_link',
            'label' => 'Contact Button 1 Link',
            'type' => 'text',
            'default' => '#',
        ],
        [
            'name' => 'contact_button2_text',
            'label' => 'Contact Button 2 Text',
            'type' => 'text',
            'default' => 'Contact Sales',
        ],
        [
            'name' => 'contact_button2_link',
            'label' => 'Contact Button 2 Link',
            'type' => 'text',
            'default' => '#',
        ],

        // Footer
        [
            'name' => 'footer_copyright_text',
            'label' => 'Footer Copyright Text',
            'type' => 'text',
            'default' => '© :year Buzz Development. | All rights reserved.',
            'description' => 'Supports :year and :app_name placeholders',
        ],

    ],
];
